apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-controller
  labels:
    app: edge-controller
spec:
  selector:
    matchLabels:
      app: edge-controller
  template:
    metadata:
      labels:
        app: edge-controller
    spec:
      nodeSelector:
        kubernetes.io/hostname: server-1
      containers:
      - name: edge-controller
        image: yonseiwinettest/edge-controller-image:latest
        #command: ["/bin/bash","-c","while true; do sleep 1000; done"]
        command: ["/bin/bash","-c","python3 build_script.py build_ext --inplace && python3 edge_controller.py --rank=0 --master_addr='10.96.0.200'"]
        ports:
        - containerPort: 30000

---

apiVersion: v1
kind: Service
metadata:
  name: edge-controller-cluster-ip-service
spec:
  clusterIP: 10.96.0.200
  ports:
  - name: pytorch-ddp-port
    port: 30000
  selector:
    app: edge-controller

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-camera
  labels:
    app: smart-camera
spec:
  selector:
    matchLabels:
      app: smart-camera
  template:
    metadata:
      labels:
        app: smart-camera
    spec:
      nodeSelector:
        kubernetes.io/hostname: wnlab-nano-002
      containers:
      - name: smart-camera
        image: yonseiwinettest/smart-camera-image:latest
        env:
        - name: MASTERADDR
          value: "10.96.0.200"
        - name: MASTERPORT
          value: "30000"
        - name: OUTPUT_NAME
          value: smart_camera_001
        - name: LAYERNAME
          value: vggnet
        - name: SSH_PASSWARD # 데이터 취합용
          value: 123asd123
        - name: SCP_ADDRESS
          value: hbp@192.168.0.2
        - name: SCP_PATH
          value: ./
        #resources:
        #  limits:
        #    nvidia.com/gpu: 1
        command: ["/bin/bash","-c","python3 build_script.py build_ext --inplace && python3 smart_camera.py --rank=1 --master_addr='10.96.0.200' --vram_limit=0.5"] #1> $(OUTPUT_NAME).txt 2> $(OUTPUT_NAME)_err.txt; sshpass -p $(SSH_PASSWARD) scp -o StrictHostKeyChecking=no $(LAYERNAME)*.txt $(SCP_ADDRESS):$(SCP_PATH);"]
        ports:
        - containerPort: 30000

---

apiVersion: v1
kind: Service
metadata:
  name: smart-camera-cluster-ip-service
spec:
  clusterIP: 10.96.0.201
  ports:
  - port: 30000
  selector:
    app: smart-camera
