apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-controller
  labels:
    app: edge-controller
spec:
  selector:
    matchLabels:
      app: edge-controller
  template:
    metadata:
      labels:
        app: edge-controller
    spec:
      nodeSelector:
        kubernetes.io/hostname: jin-tfx255
      containers:
      - name: edge-controller
        image: yhjh5302/edge-controller-image:latest
        command: ["/bin/bash","-c","while true; do sleep 1000; done"]
        #command: ["/bin/bash","-c","python3 edge_controller.py --set_gpu='false' --master_addr='10.96.0.200' --prev_port='30000'"]
        ports:
        - containerPort: 30000

---

apiVersion: v1
kind: Service
metadata:
  name: edge-controller-cluster-ip-service
spec:
  clusterIP: 10.96.0.200
  ports:
  - name: pytorch-ddp-port
    port: 30000
  selector:
    app: edge-controller

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-camera
  labels:
    app: smart-camera
spec:
  selector:
    matchLabels:
      app: smart-camera
  template:
    metadata:
      labels:
        app: smart-camera
    spec:
      nodeSelector:
        kubernetes.io/hostname: wnlab-nano-001
      containers:
      - name: smart-camera
        image: yhjh5302/smart-camera-image:latest
        env:
        - name: MASTERADDR
          value: 10.96.0.200
        - name: MASTERPORT
          value: 30000
        - name: OUTPUT_NAME
          value: smart_camera_001
        - name: SSH_PASSWARD # 데이터 취합용
          value: 123qwe123
        - name: SCP_ADDRESS
          value: wnlab@165.132.106.119
        - name: SCP_PATH
          value: ./
        #resources:
        #  limits:
        #    nvidia.com/gpu: 1
        command: ["/bin/bash","-c","python3 smart_camera.py --set_gpu='false' --master_addr='10.96.0.200' --prev_port='30000' --vram_limit=0.2 1> $(OUTPUT_NAME).txt 2> $(OUTPUT_NAME)_err.txt; sshpass -p $(SSH_PASSWARD) scp -o StrictHostKeyChecking=no $(LAYERNAME)*.txt $(SCP_ADDRESS):$(SCP_PATH);"]
        ports:
        - containerPort: 30000

---

apiVersion: v1
kind: Service
metadata:
  name: smart-camera-cluster-ip-service
spec:
  clusterIP: 10.96.0.201
  ports:
  - port: 30000
  selector:
    app: smart-camera