apiVersion: apps/v1
kind: Deployment
metadata:
  name: nano-test
  labels:
    app: nano-test
spec:
  selector:
    matchLabels:
      app: nano-test
  template:
    metadata:
      labels:
        app: nano-test
    spec:
      nodeSelector:
        kubernetes.io/hostname: wnlab-nano-001
      containers:
      - name: nano-test
        image: nvcr.io/nvidia/l4t-tensorflow:r32.6.1-tf2.5-py3
        #resources:
        #  limits:
        #    nvidia.com/gpu: 1
        command: ["/bin/bash","-c","while true; do sleep 1000; done"]
        #command: ["/bin/bash","-c","python3 AlexNetLayer1.py --set_gpu='true' --prev_addr='' --prev_port=30001 --next_addr='10.96.0.202' --next_port=30002 --vram_limit=32 --debug=1000"]
        ports:
        - containerPort: 30001

---

apiVersion: v1
kind: Service
metadata:
  name: nano-test-cluster-ip-service
spec:
  clusterIP: 10.96.0.201
  ports:
  - port: 30001
  selector:
    app: nano-test