apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-tfx255
  labels:
    app: scheduler-tfx255
spec:
  selector:
    matchLabels:
      app: scheduler-tfx255
  template:
    metadata:
      labels:
        app: scheduler-tfx255
    spec:
      nodeSelector:
        kubernetes.io/hostname: jin-tfx255
      containers:
      - name: scheduler-tfx255
        image: yhjh5302/scheduler:latest
        env:
        - name: RATIO
          value: "0.333 0.333 0.333"
        command: ["/bin/bash","-c","python3 scheduler.py --p $(RATIO)"]
        
        ports:
        - containerPort: 30050  # todo different port number
        - containerPort: 30051
        - containerPort: 30052

---

apiVersion: v1
kind: Service
metadata:
  name: scheduler-tfx255-ip-service
spec:
  clusterIP: 10.96.0.250
  ports:
  - name: alexnet-layer1
    port: 30050
  - name: alexnet-layer2
    port: 30051
  - name: alexnet-layer3
    port: 30052
  selector:
    app: scheduler-tfx255

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-w65
  labels:
    app: scheduler-w65
spec:
  selector:
    matchLabels:
      app: scheduler-w65
  template:
    metadata:
      labels:
        app: scheduler-w65
    spec:
      nodeSelector:
        kubernetes.io/hostname: jin-w65-67sf
      containers:
      - name: scheduler-w65
        image: yhjh5302/scheduler:latest
        env:
        - name: RATIO
          value: "0.5 0.5"
        command: ["/bin/bash","-c","python3 scheduler.py --p $(RATIO)"]
        
        ports:
        - containerPort: 30050
        - containerPort: 30051

---

apiVersion: v1
kind: Service
metadata:
  name: scheduler-w65-ip-service
spec:
  clusterIP: 10.96.0.251
  ports:
  - name: vggfnet-layer1
    port: 30050
  - name: vggfnet-layer2
    port: 30051
  selector:
    app: scheduler-w65

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-server
  labels:
    app: scheduler-server
spec:
  selector:
    matchLabels:
      app: scheduler-server
  template:
    metadata:
      labels:
        app: scheduler-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: server-2
      containers:
      - name: scheduler-server
        image: yhjh5302/scheduler:latest
        env:
        - name: RATIO
          value: "0.1111 0.1111 0.1111 0.1111 0.1111 0.1111 0.1111 0.1111 0.1111"
        command: ["/bin/bash","-c","python3 scheduler.py --p $(RATIO)"]
        
        ports:
        - containerPort: 30050
        - containerPort: 30051
        - containerPort: 30052
        - containerPort: 30053
        - containerPort: 30054
        - containerPort: 30055
        - containerPort: 30056
        - containerPort: 30057
        - containerPort: 30058

---

apiVersion: v1
kind: Service
metadata:
  name: scheduler-server-ip-service
spec:
  clusterIP: 10.96.0.252
  ports:
  - name: googlenet-layer1
    port: 30050
  - name: googlenet-layer2
    port: 30051
  - name: googlenet-layer3
    port: 30052
  - name: mobilenet-layer1
    port: 30053
  - name: mobilenet-layer2
    port: 30054
  - name: mobilenet-layer3
    port: 30055
  - name: vggnet-layer1
    port: 30056
  - name: vggnet-layer2
    port: 30057
  - name: vggnet-layer3
    port: 30058
  selector:
    app: scheduler-server
