apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-generator
  labels:
    app: data-generator
spec:
  selector:
    matchLabels:
      app: data-generator
  template:
    metadata:
      labels:
        app: data-generator
    spec:
      nodeSelector:
        kubernetes.io/hostname: wnlab-labtop-2
      containers:
      - name: data-generator
        image: yhjh5302/data-uploader:latest
        #image: yhjh5302/data-generator:latest
        command: ["/bin/bash","-c","while true; do sleep 1000; done"]
        #command: ["/bin/bash","-c","python3 data_uploader.py --set_gpu='false' --prev_addr='' --prev_port=30000 --next_addr='10.96.0.201' --next_port=30001"]
        #command: ["/bin/bash","-c","python3 DataGenerator.py --alexnet_prev_addr='' --alexnet_next_addr='10.96.0.201' --googlenet_prev_addr='' --googlenet_next_addr='10.96.0.211' --mobilenet_prev_addr='' --mobilenet_next_addr='10.96.0.221' --vggnet_prev_addr='' --vggnet_next_addr='10.96.0.231' --vggfnet_prev_addr='' --vggfnet_next_addr='10.96.0.241'"]
        ports:
        - containerPort: 30000
        - containerPort: 30010
        - containerPort: 30020
        - containerPort: 30030
        - containerPort: 30040

---

apiVersion: v1
kind: Service
metadata:
  name: data-generator-cluster-ip-service
spec:
  clusterIP: 10.96.0.200
  ports:
  - name: alexnet
    port: 30000
  - name: googlenet
    port: 30010
  - name: mobilenet
    port: 30020
  - name: vggnet
    port: 30030
  - name: vggfnet
    port: 30040
  selector:
    app: data-generator

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: alexnet-layer1
  labels:
    app: alexnet-layer1
spec:
  selector:
    matchLabels:
      app: alexnet-layer1
  template:
    metadata:
      labels:
        app: alexnet-layer1
    spec:
      nodeSelector:
        kubernetes.io/hostname: jin-tfx255
      containers:
      - name: alexnet-layer1
        image: yhjh5302/alexnet-layer1:latest
        #resources:
        #  limits:
        #    nvidia.com/gpu: 1
        command: ["/bin/bash","-c","python3 AlexNetLayer1.py --set_gpu='false' --prev_addr='' --prev_port=30001 --next_addr='10.96.0.202' --next_port=30002 --vram_limit=32 --debug=10000"]
        ports:
        - containerPort: 30001

---

apiVersion: v1
kind: Service
metadata:
  name: alexnet-layer1-cluster-ip-service
spec:
  clusterIP: 10.96.0.201
  ports:
  - port: 30001
  selector:
    app: alexnet-layer1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: alexnet-layer2
  labels:
    app: alexnet-layer2
spec:
  selector:
    matchLabels:
      app: alexnet-layer2
  template:
    metadata:
      labels:
        app: alexnet-layer2
    spec:
      nodeSelector:
        kubernetes.io/hostname: jin-tfx255
      containers:
      - name: alexnet-layer2
        image: yhjh5302/alexnet-layer2:latest
        #resources:
        #  limits:
        #    nvidia.com/gpu: 1
        command: ["/bin/bash","-c","python3 AlexNetLayer2.py --set_gpu='false' --prev_addr='' --prev_port=30002 --next_addr='10.96.0.203' --next_port=30003 --vram_limit=32 --debug=10000"]
        ports:
        - containerPort: 30002

---

apiVersion: v1
kind: Service
metadata:
  name: alexnet-layer2-cluster-ip-service
spec:
  clusterIP: 10.96.0.202
  ports:
  - port: 30002
  selector:
    app: alexnet-layer2

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: alexnet-layer3
  labels:
    app: alexnet-layer3
spec:
  selector:
    matchLabels:
      app: alexnet-layer3
  template:
    metadata:
      labels:
        app: alexnet-layer3
    spec:
      nodeSelector:
        kubernetes.io/hostname: jin-tfx255
      containers:
      - name: alexnet-layer3
        image: yhjh5302/alexnet-layer3:latest
        #resources:
        #  limits:
        #    nvidia.com/gpu: 1
        command: ["/bin/bash","-c","python3 AlexNetLayer3.py --set_gpu='false' --prev_addr='' --prev_port=30003 --next_addr='10.96.0.200' --next_port=30000 --vram_limit=320 --debug=10000"]
        ports:
        - containerPort: 30003

---

apiVersion: v1
kind: Service
metadata:
  name: alexnet-layer3-cluster-ip-service
spec:
  clusterIP: 10.96.0.203
  ports:
  - port: 30003
  selector:
    app: alexnet-layer3

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vggfnet-layer1
  labels:
    app: vggfnet-layer1
spec:
  selector:
    matchLabels:
      app: vggfnet-layer1
  template:
    metadata:
      labels:
        app: vggfnet-layer1
    spec:
      nodeSelector:
        kubernetes.io/hostname: jin-w65-67sf
      containers:
      - name: vggfnet-layer1
        image: yhjh5302/vggfnet-layer1:latest
        #resources:
        #  limits:
        #    nvidia.com/gpu: 1
        command: ["/bin/bash","-c","python3 VGGFNetLayer1.py --set_gpu='false' --prev_addr='' --prev_port=30041 --next_addr='10.96.0.242' --next_port=30042 --vram_limit=32 --debug=10000"]
        ports:
        - containerPort: 30041

---

apiVersion: v1
kind: Service
metadata:
  name: vggfnet-layer1-cluster-ip-service
spec:
  clusterIP: 10.96.0.241
  ports:
  - port: 30041
  selector:
    app: vggfnet-layer1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vggfnet-layer2
  labels:
    app: vggfnet-layer2
spec:
  selector:
    matchLabels:
      app: vggfnet-layer2
  template:
    metadata:
      labels:
        app: vggfnet-layer2
    spec:
      nodeSelector:
        kubernetes.io/hostname: jin-w65-67sf
      containers:
      - name: vggfnet-layer2
        image: yhjh5302/vggfnet-layer2:latest
        #resources:
        #  limits:
        #    nvidia.com/gpu: 1
        command: ["/bin/bash","-c","python3 VGGFNetLayer2.py --set_gpu='false' --prev_addr='' --prev_port=30042 --next_addr='10.96.0.200' --next_port=30040 --vram_limit=256 --debug=10000"]
        ports:
        - containerPort: 30042

---

apiVersion: v1
kind: Service
metadata:
  name: vggfnet-layer2-cluster-ip-service
spec:
  clusterIP: 10.96.0.242
  ports:
  - port: 30042
  selector:
    app: vggfnet-layer2