apiVersion: apps/v1
kind: Deployment
metadata:
  name: layer1
  labels:
    app: layer1
spec:
  selector:
    matchLabels:
      app: layer1
  template:
    metadata:
      labels:
        app: layer1
    spec:
      nodeSelector:
        kubernetes.io/hostname: jin-server
      containers:
      - name: layer1
        image: pytorch/pytorch:1.9.0-cuda11.1-cudnn8-devel
        #resources:
        #  limits:
        #    nvidia.com/gpu: 1
        command: ["/bin/bash","-c","while true; do sleep 1000; done"]
        ports:
        - containerPort: 30000

---

apiVersion: v1
kind: Service
metadata:
  name: layer1-cluster-ip-service
spec:
  clusterIP: 10.96.0.201
  ports:
  - port: 30000
  selector:
    app: layer1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: layer2
  labels:
    app: layer2
spec:
  selector:
    matchLabels:
      app: layer2
  template:
    metadata:
      labels:
        app: layer2
    spec:
      nodeSelector:
        kubernetes.io/hostname: ubuntu
      containers:
      - name: layer2
        image: yhjh5302/pytorch-rpi
        #resources:
        #  limits:
        #    nvidia.com/gpu: 1
        command: ["/bin/bash","-c","while true; do sleep 1000; done"]
        ports:
        - containerPort: 30000

---

apiVersion: v1
kind: Service
metadata:
  name: layer2-cluster-ip-service
spec:
  clusterIP: 10.96.0.202
  ports:
  - port: 30000
  selector:
    app: layer2