apiVersion: apps/v1
kind: Deployment
metadata:
  name: layer1
  labels:
    app: layer1
spec:
  selector:
    matchLabels:
      app: layer1
  template:
    metadata:
      labels:
        app: layer1
    spec:
      nodeSelector:
        kubernetes.io/hostname: jin-tfx255
      containers:
      - name: layer1
        image: pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime
        #resources:
        #  limits:
        #    nvidia.com/gpu: 1
        command: ["/bin/bash","-c","while true; do sleep 1000; done"]
        ports:
        - containerPort: 30001

---

apiVersion: v1
kind: Service
metadata:
  name: layer1-cluster-ip-service
spec:
  clusterIP: 10.96.0.201
  ports:
  - port: 30001
  selector:
    app: layer1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: layer2
  labels:
    app: layer2
spec:
  selector:
    matchLabels:
      app: layer2
  template:
    metadata:
      labels:
        app: layer2
    spec:
      nodeSelector:
        kubernetes.io/hostname: wnlab-nano-001
      containers:
      - name: layer2
        image: nvcr.io/nvidia/l4t-pytorch:r32.6.1-pth1.9-py3
        #resources:
        #  limits:
        #    nvidia.com/gpu: 1
        command: ["/bin/bash","-c","while true; do sleep 1000; done"]
        ports:
        - containerPort: 30002

---

apiVersion: v1
kind: Service
metadata:
  name: layer2-cluster-ip-service
spec:
  clusterIP: 10.96.0.202
  ports:
  - port: 30002
  selector:
    app: layer2

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: layer3
  labels:
    app: layer3
spec:
  selector:
    matchLabels:
      app: layer3
  template:
    metadata:
      labels:
        app: layer3
    spec:
      nodeSelector:
        kubernetes.io/hostname: wnlab-nano-002
      containers:
      - name: layer3
        image: nvcr.io/nvidia/l4t-pytorch:r32.6.1-pth1.9-py3
        #resources:
        #  limits:
        #    nvidia.com/gpu: 1
        command: ["/bin/bash","-c","while true; do sleep 1000; done"]
        ports:
        - containerPort: 30003

---

apiVersion: v1
kind: Service
metadata:
  name: layer3-cluster-ip-service
spec:
  clusterIP: 10.96.0.203
  ports:
  - port: 30003
  selector:
    app: layer3