from GoogLeNetModel import *

if __name__ == '__main__':
    # load dataset
    (x_train, y_train), _ = keras.datasets.cifar10.load_data()
    x_train = x_train.reshape(50000, 32, 32, 3).astype('float32') / 255

    # model training
    model = GoogLeNet(name='GoogLeNet')
    model.compile(loss='sparse_categorical_crossentropy', optimizer=tf.optimizers.SGD(learning_rate=0.001, momentum=0.9, clipnorm=1.), metrics=['accuracy'])
    model.build((None,32,32,3))
    model.summary()
    history = model.fit(x_train, y_train, batch_size=64, epochs=10)

    # saving weights
    model.conv1.save_weights('./GoogLeNet_conv1_weights', save_format='tf')
    model.conv2.save_weights('./GoogLeNet_conv2_weights', save_format='tf')
    model.conv3.save_weights('./GoogLeNet_conv3_weights', save_format='tf')
    model.inception3a_branch1.save_weights('./GoogLeNet_inception3a_branch1_weights', save_format='tf')
    model.inception3a_branch2_conv1.save_weights('./GoogLeNet_inception3a_branch2_conv1_weights', save_format='tf')
    model.inception3a_branch2_conv2.save_weights('./GoogLeNet_inception3a_branch2_conv2_weights', save_format='tf')
    model.inception3a_branch3_conv1.save_weights('./GoogLeNet_inception3a_branch3_conv1_weights', save_format='tf')
    model.inception3a_branch3_conv2.save_weights('./GoogLeNet_inception3a_branch3_conv2_weights', save_format='tf')
    model.inception3a_branch4_conv.save_weights('./GoogLeNet_inception3a_branch4_conv_weights', save_format='tf')
    model.inception3b_branch1.save_weights('./GoogLeNet_inception3b_branch1_weights', save_format='tf')
    model.inception3b_branch2_conv1.save_weights('./GoogLeNet_inception3b_branch2_conv1_weights', save_format='tf')
    model.inception3b_branch2_conv2.save_weights('./GoogLeNet_inception3b_branch2_conv2_weights', save_format='tf')
    model.inception3b_branch3_conv1.save_weights('./GoogLeNet_inception3b_branch3_conv1_weights', save_format='tf')
    model.inception3b_branch3_conv2.save_weights('./GoogLeNet_inception3b_branch3_conv2_weights', save_format='tf')
    model.inception3b_branch4_conv.save_weights('./GoogLeNet_inception3b_branch4_conv_weights', save_format='tf')
    model.inception4a_branch1.save_weights('./GoogLeNet_inception4a_branch1_weights', save_format='tf')
    model.inception4a_branch2_conv1.save_weights('./GoogLeNet_inception4a_branch2_conv1_weights', save_format='tf')
    model.inception4a_branch2_conv2.save_weights('./GoogLeNet_inception4a_branch2_conv2_weights', save_format='tf')
    model.inception4a_branch3_conv1.save_weights('./GoogLeNet_inception4a_branch3_conv1_weights', save_format='tf')
    model.inception4a_branch3_conv2.save_weights('./GoogLeNet_inception4a_branch3_conv2_weights', save_format='tf')
    model.inception4a_branch4_conv.save_weights('./GoogLeNet_inception4a_branch4_conv_weights', save_format='tf')
    model.inception4b_branch1.save_weights('./GoogLeNet_inception4b_branch1_weights', save_format='tf')
    model.inception4b_branch2_conv1.save_weights('./GoogLeNet_inception4b_branch2_conv1_weights', save_format='tf')
    model.inception4b_branch2_conv2.save_weights('./GoogLeNet_inception4b_branch2_conv2_weights', save_format='tf')
    model.inception4b_branch3_conv1.save_weights('./GoogLeNet_inception4b_branch3_conv1_weights', save_format='tf')
    model.inception4b_branch3_conv2.save_weights('./GoogLeNet_inception4b_branch3_conv2_weights', save_format='tf')
    model.inception4b_branch4_conv.save_weights('./GoogLeNet_inception4b_branch4_conv_weights', save_format='tf')
    model.inception4c_branch1.save_weights('./GoogLeNet_inception4c_branch1_weights', save_format='tf')
    model.inception4c_branch2_conv1.save_weights('./GoogLeNet_inception4c_branch2_conv1_weights', save_format='tf')
    model.inception4c_branch2_conv2.save_weights('./GoogLeNet_inception4c_branch2_conv2_weights', save_format='tf')
    model.inception4c_branch3_conv1.save_weights('./GoogLeNet_inception4c_branch3_conv1_weights', save_format='tf')
    model.inception4c_branch3_conv2.save_weights('./GoogLeNet_inception4c_branch3_conv2_weights', save_format='tf')
    model.inception4c_branch4_conv.save_weights('./GoogLeNet_inception4c_branch4_conv_weights', save_format='tf')
    model.inception4d_branch1.save_weights('./GoogLeNet_inception4d_branch1_weights', save_format='tf')
    model.inception4d_branch2_conv1.save_weights('./GoogLeNet_inception4d_branch2_conv1_weights', save_format='tf')
    model.inception4d_branch2_conv2.save_weights('./GoogLeNet_inception4d_branch2_conv2_weights', save_format='tf')
    model.inception4d_branch3_conv1.save_weights('./GoogLeNet_inception4d_branch3_conv1_weights', save_format='tf')
    model.inception4d_branch3_conv2.save_weights('./GoogLeNet_inception4d_branch3_conv2_weights', save_format='tf')
    model.inception4d_branch4_conv.save_weights('./GoogLeNet_inception4d_branch4_conv_weights', save_format='tf')
    model.inception4e_branch1.save_weights('./GoogLeNet_inception4e_branch1_weights', save_format='tf')
    model.inception4e_branch2_conv1.save_weights('./GoogLeNet_inception4e_branch2_conv1_weights', save_format='tf')
    model.inception4e_branch2_conv2.save_weights('./GoogLeNet_inception4e_branch2_conv2_weights', save_format='tf')
    model.inception4e_branch3_conv1.save_weights('./GoogLeNet_inception4e_branch3_conv1_weights', save_format='tf')
    model.inception4e_branch3_conv2.save_weights('./GoogLeNet_inception4e_branch3_conv2_weights', save_format='tf')
    model.inception4e_branch4_conv.save_weights('./GoogLeNet_inception4e_branch4_conv_weights', save_format='tf')
    model.inception5a_branch1.save_weights('./GoogLeNet_inception5a_branch1_weights', save_format='tf')
    model.inception5a_branch2_conv1.save_weights('./GoogLeNet_inception5a_branch2_conv1_weights', save_format='tf')
    model.inception5a_branch2_conv2.save_weights('./GoogLeNet_inception5a_branch2_conv2_weights', save_format='tf')
    model.inception5a_branch3_conv1.save_weights('./GoogLeNet_inception5a_branch3_conv1_weights', save_format='tf')
    model.inception5a_branch3_conv2.save_weights('./GoogLeNet_inception5a_branch3_conv2_weights', save_format='tf')
    model.inception5a_branch4_conv.save_weights('./GoogLeNet_inception5a_branch4_conv_weights', save_format='tf')
    model.inception5b_branch1.save_weights('./GoogLeNet_inception5b_branch1_weights', save_format='tf')
    model.inception5b_branch2_conv1.save_weights('./GoogLeNet_inception5b_branch2_conv1_weights', save_format='tf')
    model.inception5b_branch2_conv2.save_weights('./GoogLeNet_inception5b_branch2_conv2_weights', save_format='tf')
    model.inception5b_branch3_conv1.save_weights('./GoogLeNet_inception5b_branch3_conv1_weights', save_format='tf')
    model.inception5b_branch3_conv2.save_weights('./GoogLeNet_inception5b_branch3_conv2_weights', save_format='tf')
    model.inception5b_branch4_conv.save_weights('./GoogLeNet_inception5b_branch4_conv_weights', save_format='tf')
    model.fully_connected.save_weights('./GoogLeNet_fully_connected_weights', save_format='tf')