apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: test-gateway
  namespace: yhjin
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "*"
    port:
      name: test-ssh
      number: 2222
      protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-ssh
  namespace: yhjin
spec:
  hosts:
  - '*'
  gateways:
  - yhjin/test-gateway
  tcp:
  - match:
    - port: 2222
    route:
    - destination:
        host: test-ssh.yhjin.svc.cluster.local
        port:
          number: 2222
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ssh-policy
  namespace: yhjin
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        ports: ["2222"]
---
apiVersion: v1
kind: Service
metadata:
  name: test-ssh
  namespace: yhjin
spec:
  ports:
  - name: test-ssh
    targetPort: 2222
    port: 2222
    protocol: TCP
  selector:
    statefulset: test